Started by user [8mha:////4DlDI0t6+uXLX11pe76GRu+kT2PsFbdYdgk20GMhygYeAAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZe/dLi1CL94oyi1Mr4YgBtwcQHwgAAAA==[0mShrey Sangal
[EnvInject] - Loading node environment variables.
Building remotely on [8mha:////4P0Edm1qOx6bkpknxQaskj3cPDrZSuVDbSOOY8bnTrprAAAAox+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZx/eT83ILSktQi/fDMvJT88mKF4JzEslQAFMGkyMwAAAA=[0mWindows Slave (windows) in workspace C:\Jenkins\workspace\jpetTest
ERROR: Processing failed due to a bug in the code. Please report this to the issue tracker (https://jenkins.io/redirect/report-an-issue).
[8mha:////4Owt+nPWY0DoD8KVAniklFo5RNKeFLIewm1axEdOriXkAAAAVx+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0mV3NWzufebKBsTA0NFEYMUmgZnCA1SyAABjCCFBQC2xNaiYAAAAA==[0mjava.lang.IllegalArgumentException: C:\Users\Administrator\Documents\apache-maven-3.5.0\bin doesn't have a 'lib' subdirectory - thus cannot be a valid maven installation!
	at hudson.maven.MavenEmbedderUtils.buildClassRealm(MavenEmbedderUtils.java:89)
	at hudson.maven.MavenEmbedderUtils.getMavenVersion(MavenEmbedderUtils.java:201)
	at hudson.maven.MavenEmbedderUtils.getMavenVersion(MavenEmbedderUtils.java:191)
	at hudson.maven.MavenVersionCallable.call(MavenVersionCallable.java:69)
	at hudson.maven.MavenVersionCallable.call(MavenVersionCallable.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Unknown Source)
	at ......remote call to JNLP4-connect connection from 10.1.23.182/10.1.23.182:62013(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at hudson.FilePath.act(FilePath.java:1082)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:640)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
project=hudson.maven.MavenModuleSet@c98e672[jpetTest]
project.getModules()=[hudson.maven.MavenModule@5ce8a2ff[jpetTest/jpetStore:jpet][jpetTest/jpetStore:jpet][relativePath:C:\Users\Administrator\workspace\jpet]]
project.getRootModule()=hudson.maven.MavenModule@5ce8a2ff[jpetTest/jpetStore:jpet][jpetTest/jpetStore:jpet][relativePath:C:\Users\Administrator\workspace\jpet]
FATAL: C:\Users\Administrator\Documents\apache-maven-3.5.0\bin doesn't have a 'lib' subdirectory - thus cannot be a valid maven installation!
[8mha:////4Owt+nPWY0DoD8KVAniklFo5RNKeFLIewm1axEdOriXkAAAAVx+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0mV3NWzufebKBsTA0NFEYMUmgZnCA1SyAABjCCFBQC2xNaiYAAAAA==[0mjava.lang.IllegalArgumentException: C:\Users\Administrator\Documents\apache-maven-3.5.0\bin doesn't have a 'lib' subdirectory - thus cannot be a valid maven installation!
	at hudson.maven.MavenEmbedderUtils.buildClassRealm(MavenEmbedderUtils.java:89)
	at hudson.maven.MavenEmbedderUtils.getMavenVersion(MavenEmbedderUtils.java:201)
	at hudson.maven.MavenEmbedderUtils.getMavenVersion(MavenEmbedderUtils.java:191)
	at hudson.maven.MavenVersionCallable.call(MavenVersionCallable.java:69)
	at hudson.maven.MavenVersionCallable.call(MavenVersionCallable.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Unknown Source)
	at ......remote call to JNLP4-connect connection from 10.1.23.182/10.1.23.182:62013(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at hudson.FilePath.act(FilePath.java:1082)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:640)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Notifying upstream projects of job completion
Finished: FAILURE
